docs: Update warning about Python 3.9.0 UB, now that 3.9.1 has been released
pybind/pybind11 pull request #2719
Opened 2020-12-08 15:41 UTC by YannickJadoul

## Description

## Suggested changelog entry:

```rst

```

2020-12-08 15:53 UTC, bstaletic approved these changes
Merry ~~christmas~~ python 3.9.1.

2020-12-08 16:27 UTC, Skylion007 requested changes
Typo

2020-12-08 16:27 UTC, Skylion007 commented on README.rst
> +   which includess a `fix <https://github.com/python/cpython/pull/22670>`_
typo: "includes" line 22

2020-12-08 16:30 UTC, YannickJadoul commented on README.rst
> +   which includess a `fix <https://github.com/python/cpython/pull/22670>`_
Thanks! :-)

2020-12-08 19:04 UTC, Skylion007 approved these changes

2020-12-08 23:08 UTC, merged

2020-12-09 18:10 UTC, YannickJadoul commented
Thanks, all! :-)