Allow casting from None to a custom object
pybind/pybind11 pull request #3059
Opened 2021-06-25 06:04 UTC by crisluengo

## Description

Enables implicit casts from `None` to a custom type, by allowing custom converters to run first, and doing the check for `py::none` at the end.
This fixes #2778.

The new test case is a nice illustration:
```cpp
py::class_<NoneCastTester>(m, "NoneCastTester")
    .def(py::init<>())
    .def(py::init<int>())
    .def(py::init([](py::none const&) { return NoneCastTester{}; }));
py::implicitly_convertible<py::none, NoneCastTester>();
m.def("ok_obj_or_none", [](NoneCastTester const& foo) { return foo.answer; });
```
This allows in Python:
```python
ok_obj_or_none(NoneCastTester())  # as was allowed previously
ok_obj_or_none(None)              # this is new
```

## Suggested changelog entry:

```rst
* Allow implicit casts from Python ``None`` to a C++ class.
```

2021-06-25 06:28 UTC, crisluengo commented
There seems to be some issue downloading Catch on Windows. None of the failed tests actually ran.

2021-06-25 17:17 UTC, henryiii commented
Known issue for the last day or two. Guessing it's a networking issue on GHA's side?

2021-06-25 17:20 UTC, henryiii approved these changes
Seems fine to me, @EricCousineau-TRI or @rwgk would you like to take a look too? Also, @rwgk should we port your CI patch for now? Maybe we can get the file some other way, instead? (It's a GitHub to GitHub download that's failing on Windows only...)

2021-06-25 17:21 UTC, henryiii commented
@YannickJadoul You looked at this before, as well, along with @bstaletic, happy to take a once-over!

2021-06-25 17:25 UTC, EricCousineau-TRI requested changes
LGTM for code!

That being said, there is an existing way to admit casting from `py::none` to a different representation (custom object) by using `py::detail::type_caster<>`.
Docs: https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html
Example (in pybind11) for `std::optional<T>` caster:
https://github.com/pybind/pybind11/blob/484b0f04332fff15543d4c2a49c355d6942455fa/include/pybind11/stl.h#L281-L283

Therefore, could you better qualify your commit / PR title to reflect that?
e.g.
"fix: allow casting from None to custom object when using type_caster_generic" (impl details)
or
"fix: allow casting from None to custom object for generic types"

2021-06-25 17:37 UTC, rwgk commented
> "fix: allow casting from None to custom object for generic types"

LGTM for code, too.

Using the word "custom" puts me on the wrong track. IIUC the feature change is for `py::class_`-wrapped types and ties in with `py::implicitly_convertible`, is that correct? Would this make sense as PR title?

Enable `py::implicitly_convertible<py::none, ...>` for `py::class_`-wrapped types.

2021-06-25 19:15 UTC, crisluengo commented
@rwgk
Indeed, it is about the implicit cast to a wrapped C++ class. I have updated the PR title and the suggested change log entry.

@EricCousineau-TRI
It is maybe possible to write a `py::detail::type_caster<>`, I honestly have not tried this avenue. I have written type casters for C++ types that I wanted to correspond to native Python types (i.e. I didn't want to wrap the C++ classes). I don't know how `py::detail::type_caster<>` interacts with a wrapped class. On the other hand, why write so much code for stuff that should be generated automatically? :)

2021-06-25 19:26 UTC, rwgk commented
To get full CI coverage, could you try to adopt my ci.yml patch from the smart_holder branch here in this PR?

One way to get the diff (git pull on master & smart_holder first to be up-to-date):
```
git diff master smart_holder -- .github/workflows/ci.yml
```
Ignore the first to `+` in the diff, apply everything else.

2021-06-25 20:47 UTC, rwgk commented
The one failing CI job is safe to ignore, GHA simply ran out of macos hosts (I saw that several times before):
```
2021-06-25T20:11:48.6474262Z Found online and idle hosted runner(s) in the current repository's enterprise account that matches the required labels: 'macos-latest'
2021-06-25T20:11:48.6474317Z Waiting for a hosted runner in 'enterprise' to pick this job...
```

2021-06-25 20:48 UTC, rwgk approved these changes
@henryiii I think merging this quickly including the ci.yml patch would be great.

2021-06-25 23:06 UTC, EricCousineau-TRI commented
> `@EricCousineau-TRI`
> It is maybe possible to write a py::detail::type_caster<>, I honestly have not tried this avenue.  [...]

Haha, my b. I was more or less trying to say the same thing as Ralf - your fix is great and stand on its own, just needed to clarify the title. Sorry about that, and thanks!

2021-06-25 23:06 UTC, EricCousineau-TRI approved these changes

2021-06-26 00:56 UTC, rwgk commented
Thanks everybody! I'll merge this now with the added benefit of restoring our CI to be fully functioning.

2021-06-26 00:56 UTC, merged

2021-06-30 20:27 UTC, rwgk commented on tests/test_methods_and_attributes.py
> +def test_casts_none(msg):
Post-merge comment: `msg` is unused and can be removed. Looks like a copy-paste accident.
(I'll create a PR to fix.)