Prep-work for clang-format.
pybind/pybind11 pull request #3078
Opened 2021-07-07 00:48 UTC by rwgk

Prep-work for global clang-format (see PR #3074). NO bulk changes, just minimal changes such that the global clang-format is stable after a single pass.

This was several hours of tedious work running clang-format & clang-tidy until both are stable. Breaking out as a separate PR so that these manual changes do not have to be maintained until we are ready for the (then easy) bulk change.

Notable steps:

* Removing clang-format off-on-off directives.

* Removing stray semicolons (discovered by running clang-format v12 followed by tools/check-style.sh).

* Manually moving `// NOLINT` and `// NOLINTNEXTLINE` comments so that clang-format does not move them to the wrong places. (This was the most tedious part.)

* Manually reformatting comments related to `static_assert`s so that clang-format does not need two passes.

* `git diff -U0 --no-color HEAD^ | python3 $HOME/clone/llvm-project/clang/tools/clang-format/clang-format-diff.py -p1 -style=file -i`

## Suggested changelog entry:

```rst
Prep-work for clang-format.
```

2021-07-09 18:30 UTC, Skylion007 commented on include/pybind11/pytypes.h
> +    // clang-format on
Wouldn't disabling reflow_comments be better? Or there may be some of there might be some way to get it to recognize \rst \endrst as off and on clang-format comments.

2021-07-09 18:31 UTC, Skylion007 commented on tests/test_local_bindings.cpp
> +        // NOLINTNEXTLINE
Remove

2021-07-09 18:31 UTC, Skylion007 commented on tests/pybind11_cross_module_tests.cpp
> +        // NOLINTNEXTLINE
remove

2021-07-09 18:33 UTC, Skylion007 requested changes

2021-07-09 18:33 UTC, Skylion007 commented on tests/test_builtin_casters.cpp
> +        // NOLINTNEXTLINE(performance-unnecessary-value-param)
This can probably be fixed properly.

2021-07-09 18:33 UTC, Skylion007 commented on tests/test_kwargs_and_defaults.cpp
> +        [](int i, int j, int k, py::kwargs kwargs) { return py::make_tuple(i, j, k, kwargs); },
This should probably be fixed.

2021-07-09 21:11 UTC, rwgk commented on tests/test_local_bindings.cpp
> +        // NOLINTNEXTLINE
Fixed in #3086. I will rebase this PR.

2021-07-09 21:11 UTC, rwgk commented on tests/pybind11_cross_module_tests.cpp
> +        // NOLINTNEXTLINE
Fixed in #3086. I will rebase this PR.

2021-07-09 21:12 UTC, rwgk commented on tests/test_builtin_casters.cpp
> +        // NOLINTNEXTLINE(performance-unnecessary-value-param)
Fixed in #3086. I will rebase this PR.

2021-07-09 21:12 UTC, rwgk commented on tests/test_kwargs_and_defaults.cpp
> +        [](int i, int j, int k, py::kwargs kwargs) { return py::make_tuple(i, j, k, kwargs); },
Fixed in #3086. I will rebase this PR.

2021-07-12 21:21 UTC, rwgk commented
This one I will basically have to do from scratch after #3087 is done. At that point the only remaining clang-format related question should be how to deal with the `\rst` blocks.

2021-07-15 19:02 UTC, rwgk commented
This PR is obsolete. The only step left to do on top of the merged #3087 is somehow dealing with the `\rst` `\endrst` comment blocks. I have a simple script that inserts `// clang-format off`, `on` automatically, used for the experimental/demo draft PR #3074. There is no need for a manual step as far as I can predict, therefore this PR is obsolete.

2021-07-15 19:02 UTC, closed without merging