docs: rework CI a bit, more modern skipping
pybind/pybind11 pull request #3424
Opened 2021-10-29 02:30 UTC by henryiii

## Description

Minor docs modernization.

## Suggested changelog entry:

2021-11-08 21:33 UTC, Skylion007 commented on noxfile.py
> +        "python", "-m", "build", *session.posargs, env={"PYBIND11_GLOBAL_SDIST": "1"}
```suggestion
        sys.executable, "-m", "build", *session.posargs, env={"PYBIND11_GLOBAL_SDIST": "1"}
```

2021-11-08 21:34 UTC, Skylion007 requested changes

2021-11-08 21:34 UTC, Skylion007 commented on noxfile.py
>      session.run("python", "-m", "build", *session.posargs)
```suggestion
    session.run(sys.executable, "-m", "build", *session.posargs)
```

2021-11-08 21:35 UTC, Skylion007 commented
All the Python calls in the nox.py file should be replaced with sys.executable to ensure ti's calling the same Python module as Nox.

2021-11-08 21:41 UTC, henryiii commented
You don't _want_ the same python calling nox inside the session; you want the one set up by the session inside the virtual environment nox creates. It explicitly always prepares the path, so `python` (or any other executable) is safe, and it will show a warning if anything external to the virtual environment is used (unless you pass `external=True`).

2021-11-10 16:22 UTC, Skylion007 commented
Ah, nvm then.

2021-11-10 16:22 UTC, Skylion007 approved these changes

2021-11-10 17:13 UTC, merged