Fix caster optimization regression introduced in #3650
pybind/pybind11 pull request #3659
Opened 2022-01-28 14:47 UTC by Skylion007

## Description
So I thought about this some more, and I realized the difference between simple type and simple ancestors in the caster. A non-simple type is any ancestor who has any descendants who have multi-inheritance from C++ classes. The descendant itself is a simple type though, unless it also has descendants. This PR fixes a mistake made in #3650 where the descendants themselves can remain simple types until they are extended. Marking a type as non-simple adds some additional pointer checks in the casters and while this is an edge case, we should be careful not to undo the optimization here.

Ping @virtuald 
TLDR: Figured out what the difference is between simple_type and simple_ancestors. 
1. A type can be simple if it has MI, but has no descendants. 
2. As soon as it gets PyBind11 descendants, it ceases to be simple. 
In otherwise, `!simple_ancestors => !simple_type` only if it has PyBind11 descendants. 
I figured this out by thinking about why the rec.multiple_inheritance pathway didn't cause issues before as long multiple_inheritance was specified. The difference being that the single base pathway failed to update the type of the parent to non-simple.

## Suggested changelog entry:

```rst

```

2022-01-28 16:51 UTC, virtuald requested changes
Your explanation sounds like it captures the subtlety that I wasn't sure I had completely understood.

Can you update the documentation for the `simple_type` and `simple_ancestors`? Having it in this PR is ok, but they're really sparse on detail so making them a bit more clear would be good IMO.

2022-01-29 23:30 UTC, rwgk approved these changes
Makes sense to me, although I cannot claim that I have a full grasp of all subtleties.

Tagging @jagerman in hopes that he can confirm or correct.

2022-01-29 23:30 UTC, rwgk commented on tests/test_multiple_inheritance.py
> +    class PYMVF(m.MVF):
On chat Aaron told me this is redundant, pulled out for focused debugging.
Maybe add a comment to that effect? E.g.

`# This test is redundant but was useful for focused debugging while working on PR #3659`

2022-01-31 16:34 UTC, henryiii approved these changes
LGTM

2022-01-31 17:19 UTC, merged